#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

DOKKU_LOGSPOUT_ROOT=$DOKKU_ROOT/.logspout
source "$DOKKU_LOGSPOUT_ROOT/OPTS"

dokku logspout:start
